/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/missas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas as missas paginadas */
        get: operations["MissasController_findAll"];
        put?: never;
        /** Cria uma nova missa */
        post: operations["MissasController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca uma missa pelo ID */
        get: operations["MissasController_findOne"];
        /** Atualiza uma missa */
        put: operations["MissasController_update"];
        post?: never;
        /** Remove uma missa */
        delete: operations["MissasController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos os usuários paginados */
        get: operations["UsuariosController_findAll"];
        put?: never;
        /** Cria um novo usuário */
        post: operations["UsuariosController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca um usuário pelo ID */
        get: operations["UsuariosController_findOne"];
        /** Atualiza um usuário */
        put: operations["UsuariosController_update"];
        post?: never;
        /** Remove um usuário */
        delete: operations["UsuariosController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paroquias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas as paróquias paginadas */
        get: operations["ParoquiaController_findAll"];
        put?: never;
        /** Cria uma nova paróquia */
        post: operations["ParoquiaController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paroquias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca uma paróquia pelo ID */
        get: operations["ParoquiaController_findOne"];
        /** Atualiza uma paróquia */
        put: operations["ParoquiaController_update"];
        post?: never;
        /** Remove uma paróquia */
        delete: operations["ParoquiaController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comunidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas as comunidades paginadas */
        get: operations["ComunidadesController_findAll"];
        put?: never;
        /** Cria uma nova comunidade */
        post: operations["ComunidadesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comunidades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca uma comunidade pelo ID */
        get: operations["ComunidadesController_findOne"];
        /** Atualiza uma comunidade */
        put: operations["ComunidadesController_update"];
        post?: never;
        /** Remove uma comunidade */
        delete: operations["ComunidadesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica o usuário e retorna o token JWT */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas as cidades paginadas */
        get: operations["CidadesController_findAll"];
        put?: never;
        /** Cria uma nova cidade */
        post: operations["CidadesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cidades/proxima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca a cidade atendida mais próxima de uma posição */
        get: operations["CidadesController_findNearest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cidades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca uma cidade pelo ID */
        get: operations["CidadesController_findOne"];
        put?: never;
        post?: never;
        /** Remove uma cidade */
        delete: operations["CidadesController_remove"];
        options?: never;
        head?: never;
        /** Atualiza uma cidade */
        patch: operations["CidadesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateMissaDto: {
            /** Format: uuid */
            comunidade_id: string;
            dia_semana: number;
            horario: string;
            observacao?: string;
        };
        HorarioMissaDto: {
            /** @enum {integer} */
            dia_semana: 0 | 1 | 2 | 3 | 4 | 5 | 6;
            id: string;
            comunidade_id: string;
            horario: string;
            observacao: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        PaginationMetaDto: {
            itemCount: number;
            totalItems: number;
            itemsPerPage: number;
            totalPages: number;
            currentPage: number;
        };
        ParoquiaDto: {
            id: string;
            nome: string;
            telefone: string | null;
            siteOuRedeSocial: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        CidadeDto: {
            id: string;
            nome: string;
            estado: string;
            slug: string;
            latitude: number | null;
            longitude: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        ComunidadeComParoquiaECidadeDto: {
            paroquia: components["schemas"]["ParoquiaDto"];
            cidade: components["schemas"]["CidadeDto"] | null;
            id: string;
            paroquia_id: string;
            cidade_id: string | null;
            nome: string;
            endereco: string;
            bairro: string;
            link_google_maps: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        HorarioMissaComComunidadeDto: {
            /** @enum {integer} */
            dia_semana: 0 | 1 | 2 | 3 | 4 | 5 | 6;
            id: string;
            comunidade_id: string;
            horario: string;
            observacao: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
            comunidade: components["schemas"]["ComunidadeComParoquiaECidadeDto"];
        };
        UpdateMissaDto: Record<string, never>;
        CreateUsuarioDto: {
            nome: string;
            /** Format: email */
            email: string;
            senha: string;
            /** Format: uuid */
            cidade_id?: string;
        };
        UsuarioDto: {
            id: string;
            nome: string;
            email: string;
            /** @enum {string} */
            role: "admin" | "user";
            cidade_id: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        UpdateUsuarioDto: Record<string, never>;
        CreateParoquiaDto: {
            nome: string;
            telefone?: string;
            siteOuRedeSocial?: string;
        };
        ComunidadeComCidadeDto: {
            cidade: components["schemas"]["CidadeDto"] | null;
            id: string;
            paroquia_id: string;
            cidade_id: string | null;
            nome: string;
            endereco: string;
            bairro: string;
            link_google_maps: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        ParoquiaComComunidadesDto: {
            id: string;
            nome: string;
            telefone: string | null;
            siteOuRedeSocial: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
            comunidades: components["schemas"]["ComunidadeComCidadeDto"][];
        };
        UpdateParoquiaDto: Record<string, never>;
        CreateComunidadeDto: {
            nome: string;
            endereco: string;
            bairro: string;
            /** Format: uuid */
            paroquia_id: string;
            link_google_maps?: string;
            /** Format: uuid */
            cidade_id?: string;
        };
        ComunidadeDto: {
            id: string;
            paroquia_id: string;
            cidade_id: string | null;
            nome: string;
            endereco: string;
            bairro: string;
            link_google_maps: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        ComunidadeDetalheDto: {
            paroquia: components["schemas"]["ParoquiaDto"];
            cidade: components["schemas"]["CidadeDto"] | null;
            id: string;
            paroquia_id: string;
            cidade_id: string | null;
            nome: string;
            endereco: string;
            bairro: string;
            link_google_maps: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt: string | null;
            horarios_missa: components["schemas"]["HorarioMissaDto"][];
        };
        UpdateComunidadeDto: Record<string, never>;
        LoginDto: {
            /** Format: email */
            email: string;
            senha: string;
        };
        AccessTokenDto: {
            access_token: string;
        };
        CreateCidadeDto: {
            nome: string;
            estado: string;
            slug: string;
            latitude: number;
            longitude: number;
        };
        UpdateCidadeDto: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MissasController_findAll: {
        parameters: {
            query?: {
                dia_semana?: number;
                bairro?: string;
                cidadeId?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["HorarioMissaComComunidadeDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    MissasController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMissaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioMissaDto"];
                };
            };
        };
    };
    MissasController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioMissaComComunidadeDto"];
                };
            };
        };
    };
    MissasController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMissaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioMissaDto"];
                };
            };
        };
    };
    MissasController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioMissaDto"];
                };
            };
        };
    };
    UsuariosController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                email?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["UsuarioDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    UsuariosController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUsuarioDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    UsuariosController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    UsuariosController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUsuarioDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    UsuariosController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioDto"];
                };
            };
        };
    };
    ParoquiaController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                cidadeId?: string;
                nome?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ParoquiaComComunidadesDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    ParoquiaController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateParoquiaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParoquiaDto"];
                };
            };
        };
    };
    ParoquiaController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParoquiaComComunidadesDto"];
                };
            };
        };
    };
    ParoquiaController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateParoquiaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParoquiaDto"];
                };
            };
        };
    };
    ParoquiaController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParoquiaDto"];
                };
            };
        };
    };
    ComunidadesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                cidadeId?: string;
                nome?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ComunidadeDetalheDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    ComunidadesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComunidadeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunidadeDto"];
                };
            };
        };
    };
    ComunidadesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunidadeDetalheDto"];
                };
            };
        };
    };
    ComunidadesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateComunidadeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunidadeDto"];
                };
            };
        };
    };
    ComunidadesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunidadeDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenDto"];
                };
            };
        };
    };
    CidadesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CidadeDto"][];
                        meta: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    CidadesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCidadeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CidadeDto"];
                };
            };
        };
    };
    CidadesController_findNearest: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CidadeDto"];
                };
            };
        };
    };
    CidadesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CidadeDto"];
                };
            };
        };
    };
    CidadesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CidadeDto"];
                };
            };
        };
    };
    CidadesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCidadeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CidadeDto"];
                };
            };
        };
    };
}
